In [16]:
# import pandas and numpy
import pandas as pd
import numpy as np

url = 'http://bit.ly/autolib_dataset'

df = pd.read_csv('/content/Autolib_dataset (2) (1).csv')
df.head()

                              Address  Cars  Bluecar counter  ...  day  hour  minute
0                 2 Avenue de Suffren     0                0  ...    8    11      43
1           145 Rue Raymond Losserand     6                6  ...    6     7      24
2    2 Avenue John Fitzgerald Kennedy     3                3  ...    3    20      14
3              51 Rue EugÃ¨ne OudinÃ©     3                3  ...    4     4      37
4  6 avenue de la Porte de Champerret     3                3  ...    8    17      23

[5 rows x 25 columns]

DATA CLEANING

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Address              5000 non-null   object
 1   Cars                 5000 non-null   int64
 2   Bluecar counter      5000 non-null   int64
 3   Utilib counter       5000 non-null   int64
 4   Utilib 1.4 counter   5000 non-null   int64
 5   Charge Slots         5000 non-null   int64
 6   Charging Status      5000 non-null   object
 7   City                 5000 non-null   object
 8   Displayed comment    111 non-null    object
 9   ID                   5000 non-null   object
 10  Kind                 5000 non-null   object
 11  Geo point            5000 non-null   object
 12  Postal code          5000 non-null   int64
 13  Public name          5000 non-null   object
 14  Rental status        5000 non-null   object
 15  Scheduled at         47 non-null     object
 16  Slots                5000 non-null   int64
 17  Station type         5000 non-null   object
 18  Status               5000 non-null   object
 19  Subscription status  5000 non-null   object
 20  year                 5000 non-null   int64
 21  month                5000 non-null   int64
 22  day                  5000 non-null   int64
 23  hour                 5000 non-null   int64
 24  minute               5000 non-null   int64
dtypes: int64(12), object(13)
memory usage: 976.7+ KB

In [7]:
# Checking for any null values
df.isnull().any()

Address                False
Cars                   False
Bluecar counter        False
Utilib counter         False
Utilib 1.4 counter     False
Charge Slots           False
Charging Status        False
City                   False
Displayed comment       True
ID                     False
Kind                   False
Geo point              False
Postal code            False
Public name            False
Rental status          False
Scheduled at            True
Slots                  False
Station type           False
Status                 False
Subscription status    False
year                   False
month                  False
day                    False
hour                   False
minute                 False
dtype: bool

In [32]:
# drop the columns containing null values and geo point since its irrelevant
df.drop(['Geo point','Scheduled at','Displayed comment'], axis = 1,inplace = True)

In [12]:
df.head()

                              Address  Cars  Bluecar counter  ...  day  hour  minute
0                 2 Avenue de Suffren     0                0  ...    8    11      43
1           145 Rue Raymond Losserand     6                6  ...    6     7      24
2    2 Avenue John Fitzgerald Kennedy     3                3  ...    3    20      14
3              51 Rue EugÃ¨ne OudinÃ©     3                3  ...    4     4      37
4  6 avenue de la Porte de Champerret     3                3  ...    8    17      23

[5 rows x 22 columns]

In [9]:
# Check for any duplicates
df.duplicated().any()

False

In [15]:
# check for any null values again
df.isnull().any()

Address                False
Cars                   False
Bluecar counter        False
Utilib counter         False
Utilib 1.4 counter     False
Charge Slots           False
Charging Status        False
City                   False
ID                     False
Kind                   False
Postal code            False
Public name            False
Rental status          False
Slots                  False
Station type           False
Status                 False
Subscription status    False
year                   False
month                  False
day                    False
hour                   False
minute                 False
dtype: bool

In [14]:
df.head(1)

               Address  Cars  Bluecar counter  ...  day  hour  minute
0  2 Avenue de Suffren     0                0  ...    8    11      43

[1 rows x 22 columns]

In [35]:
# Drop row which the Bluecar counter was zero
print(df.shape)
df.drop(df[df['Bluecar counter'] == 0].index, inplace = True)
print(df.shape)

(3553, 21)
(3553, 21)

In [ ]:
# Drop the cars column because the cars encoutered are only the Bluecars
df.drop(['Cars'], axis = 1, inplace=True)

**ANALYSIS**

In [36]:
df

                                 Address  Bluecar counter  ...  hour  minute
1              145 Rue Raymond Losserand                6  ...     7      24
2       2 Avenue John Fitzgerald Kennedy                3  ...    20      14
3                 51 Rue EugÃ¨ne OudinÃ©                3  ...     4      37
4     6 avenue de la Porte de Champerret                3  ...    17      23
7            17 Rue des Luaps ProlongÃ©e                3  ...    22      13
...                                  ...              ...  ...   ...     ...
4995                 8 avenue MÃ©nelotte                2  ...    11      26
4996                   37 rue de Dantzig                4  ...    16      56
4997                      142 rue du Bac                1  ...     7       1
4998         2 avenue du Val de Fontenay                2  ...    17      27
4999                 5 Rue Henry Brisson                4  ...    10       2

[3553 rows x 21 columns]

DATA ANALYSIS

In [45]:
# Display a list of the hours in the data
df['hour'].unique()

array([ 7, 20,  4, 17, 22, 15,  9, 12, 21,  6,  3, 23, 19,  1, 10, 16, 11,
        8, 13, 18,  2,  0, 14,  5])

In [127]:
# List the days present in the data
df['day'].unique()

array([6, 3, 4, 8, 2, 5, 9, 7, 1])

From the above data there are 9 days

In [56]:
# Check the most popular hour for picking up a shared car in day one
# Create a new df
df1 = df[df['day'] == 1]
df1.reset_index(drop=True)

                                         Address  Bluecar counter  ...  hour  minute
0          2 Rue du GÃ©nÃ©ral Malleret Joinville                2  ...     4      11
1                        77 rue Edouard Vaillant                3  ...    23      36
2                               68 avenue Mozart                2  ...    21      17
3                     29 Avenue Georges Pompidou                6  ...    11      56
4            12 rue Henri Sainte-Claire DÃ©ville                4  ...     1      29
..                                           ...              ...  ...   ...     ...
405                          162 rue Championnet                2  ...     1      32
406                       115 avenue de Malakoff                4  ...     0      24
407                      21 Quai de la Tournelle                1  ...    23      37
408  188 Rue du Lieutenant-Colonel de Montbrison                4  ...     0      27
409                               142 rue du Bac                1  ...     7       1

[410 rows x 21 columns]

In [77]:
maxnumber = df1['Bluecar counter'].max()
maxnumber
x1 = list(df1[(df1['Bluecar counter'] == maxnumber)]['hour'])
print("The most popular hours (day 1) are/is:", x1)

The most popular hours (day 1) are/is: [17, 5, 0, 4, 3, 11, 20, 13, 0]

In [78]:
# Check the most popular hour for picking up a shared car in day two
# Create a new df
df2 = df[df['day'] == 2]
df2.reset_index(drop=True)

                        Address  Bluecar counter  ...  hour  minute
0         34 avenue Jean Moulin                1  ...    22      58
1             1 rue Jean Monnet                5  ...     8      37
2         18 Rue Gabriel FaurÃ©                3  ...    23      38
3              147 rue de Paris                3  ...    14      38
4            33 Rue du Ranelagh                6  ...    20      40
..                          ...              ...  ...   ...     ...
389      54 Boulevard SÃ©rurier                1  ...    21       4
390            54 rue HÃ©ricart                3  ...     6       2
391         6 avenue des Ternes                2  ...     7      54
392          42 Rue Victor Hugo                6  ...     8      30
393  6 avenue Charles-de-Gaulle                6  ...     4      43

[394 rows x 21 columns]

In [80]:
maxnumber = df2['Bluecar counter'].max()
maxnumber
x2 = list(df2[(df2['Bluecar counter'] == maxnumber)]['hour'])
print("The most popular hours (day 2) are/is:", x2)

The most popular hours (day 2) are/is: [8]

In [81]:
# Check the most popular hour for picking up a shared car in day three
# Create a new df
df3 = df[df['day'] == 3]
df3.reset_index(drop=True)

                              Address  Bluecar counter  ...  hour  minute
0    2 Avenue John Fitzgerald Kennedy                3  ...    20      14
1    203 Rue du Faubourg-Saint-Martin                2  ...     9      40
2                      21 rue Miollis                4  ...     1      22
3        38 ter rue du Mont ValÃ©rien                3  ...    16      22
4         5 rue FrÃ©dÃ©rick LemaÃ®tre                5  ...     3      48
..                                ...              ...  ...   ...     ...
433               6 rue Isidore Nerat                4  ...     2      25
434       36 avenue de la RÃ©publique                3  ...    20      57
435                     26 rue HuchÃ©                1  ...    12      53
436       63 Boulevard Richard Lenoir                4  ...     8       3
437          16 Rue Charles de Gaulle                3  ...     4       3

[438 rows x 21 columns]

In [82]:
maxnumber = df3['Bluecar counter'].max()
maxnumber
x3 = list(df3[(df3['Bluecar counter'] == maxnumber)]['hour'])
print("The most popular hours (day 3) are/is:", x3)

The most popular hours (day 3) are/is: [2, 1, 4, 4, 7]

In [83]:
# Check the most popular hour for picking up a shared car in day four
# Create a new df
df4 = df[df['day'] == 4]
df4.reset_index(drop=True)

                             Address  Bluecar counter  ...  hour  minute
0             51 Rue EugÃ¨ne OudinÃ©                3  ...     4      37
1        17 Rue des Luaps ProlongÃ©e                3  ...    22      13
2       41 boulevard de Rochechouart                6  ...    15       2
3         15 avenue Ãmile Deschanel                2  ...    23      27
4              16 rue Claude Bernard                1  ...    13       3
..                               ...              ...  ...   ...     ...
417            10 rue Jacques Mazaud                2  ...    19      43
418                 1 rue FrÃ©pillon                3  ...     7      26
419  6 place du PrÃ©sident Mithouard                2  ...     2      35
420                37 rue de Dantzig                4  ...    16      56
421      2 avenue du Val de Fontenay                2  ...    17      27

[422 rows x 21 columns]

In [84]:
maxnumber = df4['Bluecar counter'].max()
maxnumber
x4 = list(df4[(df4['Bluecar counter'] == maxnumber)]['hour'])
print("The most popular hours (day 4) are/is:", x4)

The most popular hours (day 4) are/is: [4, 10]

In [85]:
# Check the most popular hour for picking up a shared car in day five
# Create a new df
df5 = df[df['day'] == 5]
df5.reset_index(drop=True)

                                Address  Bluecar counter  ...  hour  minute
0    6 avenue de la Porte de Champerret                5  ...    12      22
1                  2 Place de Catalogne                3  ...     6      16
2                          5 rue Vauban                5  ...     3       6
3             2 avenue de l'Ãpi dâOr                6  ...     7       5
4                        14 rue Censier                2  ...     2      35
..                                  ...              ...  ...   ...     ...
427           158 boulevard de Charonne                4  ...     6      24
428               1 rue Claude Terrasse                6  ...    20      33
429                     11 rue d'Artois                2  ...    15      44
430                2 Avenue RenÃ© Fonck                1  ...    18      34
431                62 Avenue Parmentier                4  ...    23      30

[432 rows x 21 columns]

In [86]:
maxnumber = df5['Bluecar counter'].max()
maxnumber
x5 = list(df5[(df5['Bluecar counter'] == maxnumber)]['hour'])
print("The most popular hours (day 5) are/is:", x5)

The most popular hours (day 5) are/is: [21, 12, 9, 6]

In [128]:
# Check the most popular hour for picking up a shared car in day six
# Create a new df
df6 = df[df['day'] == 6]
df6.reset_index(drop=True)

                          Address  Bluecar counter  ...  hour  minute
0       145 Rue Raymond Losserand                6  ...     7      24
1    12 Rue Francis de PressensÃ©                1  ...     9      20
2                 16 rue Guynemer                1  ...    19      53
3                5 rue des Ecoles                4  ...    11      51
4    42 bis avenue Georges Mandel                5  ...    18      25
..                            ...              ...  ...   ...     ...
370   18 avenue du MarÃ©chal Juin                1  ...     4      14
371         62 rue Victor Beausse                4  ...    15      49
372  4 avenue de la SÅur Rosalie                1  ...     9      14
373                3 Rue Mongenot                4  ...     7      28
374           8 avenue MÃ©nelotte                2  ...    11      26

[375 rows x 21 columns]

In [129]:
maxnumber = df6['Bluecar counter'].max()
maxnumber
x6 = list(df6[(df6['Bluecar counter'] == maxnumber)]['hour'])
print("The most popular hours (day 6) are/is:", x6)

The most popular hours (day 6) are/is: [0, 7, 11, 6, 13, 0]

In [130]:
# Check the most popular hour for picking up a shared car in day seven
# Create a new df
df7 = df[df['day'] == 7]
df7.reset_index(drop=True)

                                          Address  ...  minute
0                      37 avenue Georges Pompidou  ...      32
1                                59 avenue Reille  ...       6
2                             11 rue de vincennes  ...      11
3                       229 Rue Raymond Losserand  ...      31
4                           34 avenue Jean Moulin  ...      22
..                                            ...  ...     ...
302                           97 Rue de Charenton  ...      48
303                  103 avenue Charles de Gaulle  ...      20
304                          41 Boulevard Pasteur  ...      59
305                            7 Rue Francois 1er  ...       8
306  56 avenue du MarÃ©chal de Lattre de Tassigny  ...      43

[307 rows x 21 columns]

In [131]:
maxnumber = df7['Bluecar counter'].max()
maxnumber
x7 = list(df7[(df7['Bluecar counter'] == maxnumber)]['hour'])
print("The most popular hours (day 7) are/is:", x7)

The most popular hours (day 7) are/is: [15, 13, 16]

In [132]:
# Check the most popular hour for picking up a shared car in day eight
# Create a new df
df8 = df[df['day'] == 8]
df8.reset_index(drop=True)

                                Address  Bluecar counter  ...  hour  minute
0    6 avenue de la Porte de Champerret                3  ...    17      23
1                        14 rue Sorbier                1  ...    17      23
2                        123 Grande Rue                2  ...     3       9
3             229 Rue Raymond Losserand                5  ...     8      22
4                1 rue Jacques Duchesne                3  ...    10      55
..                                  ...              ...  ...   ...     ...
348              23 Boulevard Delessert                3  ...     3      27
349                     20 Rue Gambetta                5  ...    14       0
350                  6 place Abel Gance                6  ...     6      41
351                        62 Rue Ramey                5  ...    11       0
352                 5 Rue Henry Brisson                4  ...    10       2

[353 rows x 21 columns]

In [133]:
maxnumber = df8['Bluecar counter'].max()
maxnumber
x8 = list(df8[(df8['Bluecar counter'] == maxnumber)]['hour'])
print("The most popular hours (day 8) are/is:", x8)

The most popular hours (day 8) are/is: [20, 13, 4]

In [135]:
# Check the most popular hour for picking up a shared car in day nine
# Create a new df
df9 = df[df['day'] == 9]
df9.reset_index(drop=True)

                    Address  Bluecar counter  Utilib counter  ...  day  hour minute
0    182 Boulevard Voltaire                6               0  ...    9    12     14
1     26 villa Croix-Nivert                5               0  ...    9    20     58
2      11 avenue RenÃ© Coty                4               0  ...    9    21     31
3          6 rue de Londres                3               0  ...    9    10     28
4         41 rue de Tolbiac                3               0  ...    9    19     49
..                      ...              ...             ...  ...  ...   ...    ...
417  32 rue Robert Marchand                6               0  ...    9     1     52
418             2 Rue Duroc                2               1  ...    9    14     35
419          46 rue de Rome                2               0  ...    9     0     31
420     22 rue de Normandie                5               1  ...    9     3      8
421           18 Rue Balard                5               0  ...    9    13     34

[422 rows x 21 columns]

In [136]:
maxnumber = df9['Bluecar counter'].max()
maxnumber
x9 = list(df8[(df8['Bluecar counter'] == maxnumber)]['hour'])
print("The most popular hours (day 9) are/is:", x9)

The most popular hours (day 9) are/is: [13, 3, 13, 12, 17, 5]

In [139]:
print("The most popular hours (day 1) are/is:", x1)
print("The most popular hours (day 2) are/is:", x2)
print("The most popular hours (day 3) are/is:", x3)
print("The most popular hours (day 4) are/is:", x4)
print("The most popular hours (day 5) are/is:", x5)
print("The most popular hours (day 6) are/is:", x6)
print("The most popular hours (day 7) are/is:", x7)
print("The most popular hours (day 8) are/is:", x8)
print("The most popular hours (day 9) are/is:", x9)

The most popular hours (day 1) are/is: [17, 5, 0, 4, 3, 11, 20, 13, 0]
The most popular hours (day 2) are/is: [8]
The most popular hours (day 3) are/is: [2, 1, 4, 4, 7]
The most popular hours (day 4) are/is: [4, 10]
The most popular hours (day 5) are/is: [21, 12, 9, 6]
The most popular hours (day 6) are/is: [0, 7, 11, 6, 13, 0]
The most popular hours (day 7) are/is: [15, 13, 16]
The most popular hours (day 8) are/is: [20, 13, 4]
The most popular hours (day 9) are/is: [13, 3, 13, 12, 17, 5]

In [138]:
popular = []
popular.extend(x1)
popular.extend(x2)
popular.extend(x3)
popular.extend(x4)
popular.extend(x5)
popular.extend(x6)
popular.extend(x7)
popular.extend(x8)
popular.extend(x9)

In [140]:
popular

[17,
 5,
 0,
 4,
 3,
 11,
 20,
 13,
 0,
 8,
 2,
 1,
 4,
 4,
 7,
 4,
 10,
 21,
 12,
 9,
 6,
 0,
 7,
 11,
 6,
 13,
 0,
 15,
 13,
 16,
 20,
 13,
 4,
 13,
 3,
 13,
 12,
 17,
 5]

In [141]:
# Calculate the mode
import collections

# calculate the frequency of each item
data = collections.Counter(popular)
data_list = dict(data)

# Print the items with frequency
print(data_list)

# Find the highest frequency
max_value = max(list(data.values()))
mode_val = [num for num, freq in data_list.items() if freq == max_value]
if len(mode_val) == len(popular):
   print("No mode in the list")
else:
   print("The Mode of the list is : " + ', '.join(map(str, mode_val)))

{17: 2, 5: 2, 0: 4, 4: 5, 3: 2, 11: 2, 20: 2, 13: 6, 8: 1, 2: 1, 1: 1, 7: 2, 10: 1, 21: 1, 12: 2, 9: 1, 6: 2, 15: 1, 16: 1}
The Mode of the list is : 13

From The above analysis the most popular hour of the day for picking up a shared electric car is the 13th hour.